openapi: 3.0.3
info:
  title: WinkDashboard
  description: ''
  version: 1.0.0
servers:
  -
    url: 'https://refer-friend.tw-dev.com'
paths:
  /api/referred/upsert:
    post:
      summary: "Upsert Referred Friend's Status"
      operationId: upsertReferredFriendsStatus
      description: "Uses the match_* fields to update a Referred friend, and sets the status.\nIf no match is found a new Referred Friend will be created with the given status."
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Upsert Successful'
                properties:
                  message:
                    type: string
                    example: 'Upsert Successful'
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                referees:
                  type: array
                  description: 'the list of Referred friends to upsert'
                  example:
                    - []
                  items:
                    type: object
                    properties:
                      match_email:
                        type: string
                        description: 'Must be a valid email address.'
                        example: gerlach.johathan@example.com
                      match_phone_number:
                        type: string
                        description: 'Must be at least 10 characters. Must not be greater than 50 characters.'
                        example: '+61 5054 43251'
                      match_first_name:
                        type: string
                        description: 'Must be at least 2 characters. Must not be greater than 50 characters.'
                        example: cyviiatfvmmscxhr
                      match_last_name:
                        type: string
                        description: 'Must be at least 2 characters. Must not be greater than 50 characters.'
                        example: eotjtmrfrfb
                      new_status:
                        type: string
                        description: 'Must be one of <code>form_completed</code>, <code>not_interested</code>, <code>meeting_booked</code>, <code>ineligible</code>, <code>pension_boost_eligible</code>, <code>loan_eligible</code>, <code>loan_approved</code>, or <code>pension_boost_approved</code>.'
                        example: loan_eligible
                    required:
                      - match_email
                      - match_phone_number
                      - match_first_name
                      - match_last_name
                      - new_status
              required:
                - referees
  /api/referrer/create:
    post:
      summary: 'Create New Referrers'
      operationId: createNewReferrers
      description: "creates new referrer from an email address.\nthis referrer will be email a form to refer friends with"
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'created x new referrers'
                properties:
                  message:
                    type: string
                    example: 'created x new referrers'
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                referrers:
                  type: array
                  description: ''
                  example:
                    - quidem
                  items:
                    type: string
              required:
                - referrers
  /api/login:
    post:
      summary: 'Login to the API'
      operationId: loginToTheAPI
      description: "requires an email & password. returns an API token to use with the other endpoints\ncontact a wink admin to get your account setup"
      parameters: []
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  token: 2060|dEKg7dU3vespqTYTuGa1wpkUPGkKISJsWav2XH9p
                properties:
                  token:
                    type: string
                    example: 2060|dEKg7dU3vespqTYTuGa1wpkUPGkKISJsWav2XH9p
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'the email to user.'
                  example: steuber.ray@example.net
                password:
                  type: string
                  description: 'the users password.'
                  example: '].?j8Br9f'
              required:
                - email
                - password
      security: []
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
